MOSQUITO_IMAGE=dev-v5.6.4-client-direct
MOSQUITO_BUILD_DATE=2026-09-08
MOSQUITO_BOARD_PACKAGE=2.18-1
MOSQUITO_SOURCE_STATE=client-direct-bb7b92a-worktree
MOSQUITO_CAMERA_MODES=camera-test0,camera-test,camera-test1,camera-test1-focus
MOSQUITO_PHOTO_METADATA=3
