MOSQUITO_IMAGE=dev-v5.6.3-usb0-adb-autostart
MOSQUITO_BUILD_DATE=2026-09-04
MOSQUITO_BOARD_PACKAGE=2.17-1
MOSQUITO_SOURCE_STATE=auto-adb-rc-final-cdf51dd
MOSQUITO_CAMERA_MODES=camera-test0,camera-test,camera-test1,camera-test1-focus
MOSQUITO_PHOTO_METADATA=2
