MOSQUITO_IMAGE=dev-v5.6.5-remote-learn
MOSQUITO_BUILD_DATE=2026-09-14
MOSQUITO_BOARD_PACKAGE=2.19-1
MOSQUITO_SOURCE_STATE=remote-learn-f9be772-worktree
MOSQUITO_CAMERA_MODES=camera-test0,camera-test,camera-test1,camera-test1-focus
MOSQUITO_PHOTO_METADATA=3
